"use client";
import { useRouter } from "next/navigation";
import { useSessionStore } from "@/store/session";

export function SummaryModal() {
  const router = useRouter();
  const { summary, summaryLoading, clearSession } = useSessionStore();

  function handleClose() {
    clearSession();
    router.push("/dashboard");
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-ink-950/80 backdrop-blur-md animate-fade-in">
      <div className="w-full max-w-2xl glass-strong rounded-3xl shadow-panel overflow-hidden animate-slide-up">
        {/* Header */}
        <div className="px-6 pt-6 pb-4 border-b border-white/5">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-signal/20 border border-signal/30 flex items-center justify-center">
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                <path d="M2 4h12M2 8h8M2 12h6" stroke="#4B85F0" strokeWidth="1.5" strokeLinecap="round" />
              </svg>
            </div>
            <div>
              <h2 className="text-base font-bold text-white">Session summary</h2>
              <p className="text-xs text-neutral-500 mt-0.5">Generated by Lab Brain</p>
            </div>
          </div>
        </div>

        {/* Body */}
        <div className="px-6 py-5 max-h-[60vh] overflow-y-auto">
          {summaryLoading ? (
            <div className="flex flex-col items-center justify-center py-10 gap-4">
              <div className="w-10 h-10 rounded-full border-2 border-signal/30 border-t-signal animate-spin" />
              <p className="text-sm text-neutral-500">Generating summary…</p>
            </div>
          ) : summary ? (
            <div className="prose-sm">
              {summary.split("\n").map((line, i) => {
                if (line.startsWith("## ")) {
                  return (
                    <h3 key={i} className="text-sm font-semibold text-neutral-200 mt-4 mb-2 first:mt-0">
                      {line.replace("## ", "")}
                    </h3>
                  );
                }
                if (line.startsWith("- ")) {
                  return (
                    <div key={i} className="flex items-start gap-2 mb-1">
                      <span className="text-signal mt-0.5 shrink-0">·</span>
                      <span className="text-sm text-neutral-300">{line.replace("- ", "")}</span>
                    </div>
                  );
                }
                if (line.trim() === "") return <div key={i} className="h-2" />;
                return (
                  <p key={i} className="text-sm text-neutral-300 mb-1">
                    {line}
                  </p>
                );
              })}
            </div>
          ) : (
            <p className="text-sm text-neutral-500 text-center py-6">
              No summary available for this session.
            </p>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-white/5 flex items-center justify-between">
          {summary && (
            <button
              onClick={() => {
                const blob = new Blob([summary], { type: "text/plain" });
                const url = URL.createObjectURL(blob);
                const a = document.createElement("a");
                a.href = url;
                a.download = "session-summary.md";
                a.click();
                URL.revokeObjectURL(url);
              }}
              className="flex items-center gap-2 text-xs text-neutral-500 hover:text-white transition-colors"
            >
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                <path d="M6 1v7M3 5l3 3 3-3M1 10h10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Download .md
            </button>
          )}
          <button
            onClick={handleClose}
            className="ml-auto px-5 py-2 rounded-xl bg-signal hover:bg-signal-light text-white text-sm font-semibold transition-colors"
          >
            Back to dashboard
          </button>
        </div>
      </div>
    </div>
  );
}
